[package]
name = "cargo-light"
version = "0.1.0"
authors = ["Fisher Darling <fdarlingco@gmail.com>"]
license = "Apache-2.0/MIT"
readme = "README.md"
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "parsing"]
keywords = ["cargo", "plugin", "statistics"]

[dependencies]
syn = {version="*", features=["parsing", "printing", "clone-impls", "full", "extra-traits", "visit", "fold"]}
clap = "*"
proc-macro2 = {version="*", cfg=["procmacro2_semver_exempt"]}
